// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aczdwxhjdaljeflbsmwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjemR3eGhqZGFsamVmbGJzbXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODQyNjksImV4cCI6MjA3MzE2MDI2OX0.Yz4Y2MiMypPj5dc7gnVbQ1SKHhwHPC4t0AzZZsRHGLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});